// OPRE NATURE — catalogue data
// Published automatically from the admin dashboard (Settings > Publish to GitHub).
// This is the LIVE catalogue: the public site, print/PDF export, and "Reset to original"
// in the admin dashboard all use this as the canonical baseline.
//
// Plain classic script (no ES modules) so the app runs from a double-clicked file:// HTML file
// with no local server required. Exposes everything on window.Opre.Data.
(function (global) {
  'use strict';

  const ORIGINAL_CATEGORIES = [
  {
    "id": "oils",
    "name": "Olive Oils & Vegetable Oils",
    "order": 1
  },
  {
    "id": "honey",
    "name": "Honey & Bee Products",
    "order": 2
  },
  {
    "id": "tahini-zaatar",
    "name": "Tahini, Sesame, Zaatar & Sumac",
    "order": 3
  },
  {
    "id": "olives",
    "name": "Olives",
    "order": 4
  },
  {
    "id": "pickles",
    "name": "Pickles & Preserved Vegetables",
    "order": 5
  },
  {
    "id": "molasses-vinegars",
    "name": "Molasses, Vinegars & Natural Acids",
    "order": 6
  },
  {
    "id": "jams",
    "name": "Jams & Fruit Preserves",
    "order": 7
  },
  {
    "id": "syrups-waters",
    "name": "Traditional Syrups & Floral Waters",
    "order": 8
  },
  {
    "id": "dried-fruits",
    "name": "Dried Fruits, Dates & Nuts",
    "order": 9
  },
  {
    "id": "tomato",
    "name": "Tomato Products & Sauces",
    "order": 10
  },
  {
    "id": "liqueurs",
    "name": "Traditional Liqueurs",
    "order": 11
  },
  {
    "id": "gift-boxes",
    "name": "Gift Boxes",
    "order": 12
  },
  {
    "id": "other",
    "name": "Other Traditional Specialities",
    "order": 13
  }
];

  const ORIGINAL_PRODUCTS = [
  {
    "id": "olive-oil-1-5-l-001-oils",
    "categoryId": "oils",
    "name": "Olive oil 1.5 L",
    "lebaneseName": "",
    "description": "Naturally pressed oil from our fields, bottled in retail and professional formats.",
    "format": "1.5 L",
    "price": 16,
    "currency": "USD",
    "priceBasis": "item",
    "order": 1,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-19"
  },
  {
    "id": "olive-oil-500-ml-002-oils",
    "categoryId": "oils",
    "name": "Olive oil 500 ml",
    "lebaneseName": "",
    "description": "Naturally pressed oil from our fields, bottled in retail and professional formats.",
    "format": "500 ml",
    "price": 5.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 2,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-19"
  },
  {
    "id": "olive-oil-750-ml-003-oils",
    "categoryId": "oils",
    "name": "Olive oil 750 ml",
    "lebaneseName": "",
    "description": "Naturally pressed oil from our fields, bottled in retail and professional formats.",
    "format": "750 ml",
    "price": 8.25,
    "currency": "USD",
    "priceBasis": "item",
    "order": 3,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olive-oil-8-kg-004-oils",
    "categoryId": "oils",
    "name": "Olive Oil 8 kg",
    "lebaneseName": "",
    "description": "Naturally pressed oil from our fields, bottled in retail and professional formats.",
    "format": "8 kg",
    "price": 77,
    "currency": "USD",
    "priceBasis": "item",
    "order": 4,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olive-oil-extra-virgin-16kg-005-oils",
    "categoryId": "oils",
    "name": "Olive oil Extra Virgin 16KG",
    "lebaneseName": "",
    "description": "Naturally pressed oil from our fields, bottled in retail and professional formats.",
    "format": "16KG",
    "price": 153,
    "currency": "USD",
    "priceBasis": "item",
    "order": 5,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olive-oil-extra-virgin-3l-006-oils",
    "categoryId": "oils",
    "name": "Olive oil Extra Virgin 3L",
    "lebaneseName": "",
    "description": "Naturally pressed oil from our fields, bottled in retail and professional formats.",
    "format": "3L",
    "price": 31.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 6,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olive-oil-regular-16-kg-011-oils",
    "categoryId": "oils",
    "name": "Olive Oil Regular 16 kg",
    "lebaneseName": "",
    "description": "Naturally pressed oil from our fields, bottled in retail and professional formats.",
    "format": "16 kg",
    "price": 75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 11,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olive-oil-tank-17-l-012-oils",
    "categoryId": "oils",
    "name": "Olive oil tank 17 L",
    "lebaneseName": "",
    "description": "Naturally pressed oil from our fields, bottled in retail and professional formats.",
    "format": "17 L",
    "price": 153,
    "currency": "USD",
    "priceBasis": "item",
    "order": 12,
    "active": false,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sunflower-700-ml-013-oils",
    "categoryId": "oils",
    "name": "Sunflower oil 700 ml",
    "lebaneseName": "",
    "description": "Naturally pressed oil from our fields, bottled in retail and professional formats.",
    "format": "700 ml",
    "price": 1.29,
    "currency": "USD",
    "priceBasis": "item",
    "order": 13,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sunflower-oil-1-8-l-014-oils",
    "categoryId": "oils",
    "name": "Sunflower oil 1.8 L",
    "lebaneseName": "",
    "description": "Naturally pressed oil from our fields, bottled in retail and professional formats.",
    "format": "1.8 L",
    "price": 3.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 14,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sunflower-oil-6-l-015-oils",
    "categoryId": "oils",
    "name": "Sunflower oil 6 L",
    "lebaneseName": "",
    "description": "Naturally pressed oil from our fields, bottled in retail and professional formats.",
    "format": "6 L",
    "price": 10.6,
    "currency": "USD",
    "priceBasis": "item",
    "order": 15,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sunflower-oil-900-ml-016-oils",
    "categoryId": "oils",
    "name": "Sunflower oil 900 ml",
    "lebaneseName": "",
    "description": "Naturally pressed oil from our fields, bottled in retail and professional formats.",
    "format": "900 ml",
    "price": 2,
    "currency": "USD",
    "priceBasis": "item",
    "order": 16,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sunflower-oil-9l-017-oils",
    "categoryId": "oils",
    "name": "Sunflower oil 9L",
    "lebaneseName": "",
    "description": "Naturally pressed oil from our fields, bottled in retail and professional formats.",
    "format": "9L",
    "price": 16,
    "currency": "USD",
    "priceBasis": "item",
    "order": 17,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "creamy-honey-500-g-001-honey",
    "categoryId": "honey",
    "name": "Creamy Honey 500 g",
    "lebaneseName": "",
    "description": "Pure, naturally harvested bee product from local hives.",
    "format": "500 g",
    "price": 18.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 1,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "honey-wax-002-honey",
    "categoryId": "honey",
    "name": "Honey Wax",
    "lebaneseName": "",
    "description": "Pure, naturally harvested bee product from local hives.",
    "format": "",
    "price": 25,
    "currency": "USD",
    "priceBasis": "item",
    "order": 2,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "oak-honey-1-kg-003-honey",
    "categoryId": "honey",
    "name": "Oak Honey 1 kg",
    "lebaneseName": "",
    "description": "Pure, naturally harvested bee product from local hives.",
    "format": "1 kg",
    "price": 33,
    "currency": "USD",
    "priceBasis": "item",
    "order": 3,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "oak-honey-500g-005-honey",
    "categoryId": "honey",
    "name": "Oak Honey 500g",
    "lebaneseName": "",
    "description": "Pure, naturally harvested bee product from local hives.",
    "format": "500g",
    "price": 15.25,
    "currency": "USD",
    "priceBasis": "item",
    "order": 5,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pollen-225-g-007-honey",
    "categoryId": "honey",
    "name": "Pollen 225 g",
    "lebaneseName": "",
    "description": "Pure, naturally harvested bee product from local hives.",
    "format": "225 g",
    "price": 10.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 7,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pollen-450-g-008-honey",
    "categoryId": "honey",
    "name": "Pollen 450 g",
    "lebaneseName": "",
    "description": "Pure, naturally harvested bee product from local hives.",
    "format": "450 g",
    "price": 20,
    "currency": "USD",
    "priceBasis": "item",
    "order": 8,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "propolis-drop-15-g-009-honey",
    "categoryId": "honey",
    "name": "Propolis drop 15 g",
    "lebaneseName": "",
    "description": "Pure, naturally harvested bee product from local hives.",
    "format": "15 g",
    "price": 15,
    "currency": "USD",
    "priceBasis": "item",
    "order": 9,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "royal-jelly-010-honey",
    "categoryId": "honey",
    "name": "Royal jelly",
    "lebaneseName": "",
    "description": "Pure, naturally harvested bee product from local hives.",
    "format": "",
    "price": 20,
    "currency": "USD",
    "priceBasis": "item",
    "order": 10,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sesame-001-tahini-zaatar",
    "categoryId": "tahini-zaatar",
    "name": "Sesame",
    "lebaneseName": "",
    "description": "Stone-ground sesame paste and traditional herb blends, prepared the homemade way.",
    "format": "",
    "price": 9,
    "currency": "USD",
    "priceBasis": "item",
    "order": 1,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sesame-250g-002-tahini-zaatar",
    "categoryId": "tahini-zaatar",
    "name": "Sesame 250g",
    "lebaneseName": "",
    "description": "Stone-ground sesame paste and traditional herb blends, prepared the homemade way.",
    "format": "250g",
    "price": 2.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 2,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sesame-500g-003-tahini-zaatar",
    "categoryId": "tahini-zaatar",
    "name": "Sesame 500g",
    "lebaneseName": "",
    "description": "Stone-ground sesame paste and traditional herb blends, prepared the homemade way.",
    "format": "500g",
    "price": 5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 3,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sesame-nay-ma2shour-004-tahini-zaatar",
    "categoryId": "tahini-zaatar",
    "name": "Sesame nay ma2shour",
    "lebaneseName": "",
    "description": "Stone-ground sesame paste and traditional herb blends, prepared the homemade way.",
    "format": "",
    "price": 3.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 4,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sumac-006-tahini-zaatar",
    "categoryId": "tahini-zaatar",
    "name": "Sumac",
    "lebaneseName": "",
    "description": "Stone-ground sesame paste and traditional herb blends, prepared the homemade way.",
    "format": "",
    "price": 17,
    "currency": "USD",
    "priceBasis": "item",
    "order": 6,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sumac-250-007-tahini-zaatar",
    "categoryId": "tahini-zaatar",
    "name": "Sumac 250",
    "lebaneseName": "",
    "description": "Stone-ground sesame paste and traditional herb blends, prepared the homemade way.",
    "format": "",
    "price": 4.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 7,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sumac-500-008-tahini-zaatar",
    "categoryId": "tahini-zaatar",
    "name": "Sumac 500",
    "lebaneseName": "",
    "description": "Stone-ground sesame paste and traditional herb blends, prepared the homemade way.",
    "format": "",
    "price": 9,
    "currency": "USD",
    "priceBasis": "item",
    "order": 8,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "tahini-thineh-400g-piece-009-tahini-zaatar",
    "categoryId": "tahini-zaatar",
    "name": "Tahini (Thineh) 400g - piece",
    "lebaneseName": "Thineh",
    "description": "Stone-ground sesame paste and traditional herb blends, prepared the homemade way.",
    "format": "400g",
    "price": 1.95,
    "currency": "USD",
    "priceBasis": "item",
    "order": 9,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "tahini-thineh-400g-box-010-tahini-zaatar",
    "categoryId": "tahini-zaatar",
    "name": "Tahini (Thineh) 400g box",
    "lebaneseName": "Thineh",
    "description": "Stone-ground sesame paste and traditional herb blends, prepared the homemade way.",
    "format": "",
    "price": 23.4,
    "currency": "USD",
    "priceBasis": "item",
    "order": 10,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "tahini-thineh-800-g-011-tahini-zaatar",
    "categoryId": "tahini-zaatar",
    "name": "Tahini (Thineh) 800 g",
    "lebaneseName": "Thineh",
    "description": "Stone-ground sesame paste and traditional herb blends, prepared the homemade way.",
    "format": "800 g",
    "price": 3.33,
    "currency": "USD",
    "priceBasis": "item",
    "order": 11,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "tahini-thineh-extra-9-kg-012-tahini-zaatar",
    "categoryId": "tahini-zaatar",
    "name": "Tahini (Thineh) Extra 9 kg",
    "lebaneseName": "Thineh",
    "description": "Stone-ground sesame paste and traditional herb blends, prepared the homemade way.",
    "format": "9 kg",
    "price": 38,
    "currency": "USD",
    "priceBasis": "item",
    "order": 12,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "tahini-thineh-extra-pail-18-kg-013-tahini-zaatar",
    "categoryId": "tahini-zaatar",
    "name": "Tahini (Thineh) Extra pail 18 kg",
    "lebaneseName": "Thineh",
    "description": "Stone-ground sesame paste and traditional herb blends, prepared the homemade way.",
    "format": "18 kg",
    "price": 75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 13,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "tahini-thineh-pail-4-kg-014-tahini-zaatar",
    "categoryId": "tahini-zaatar",
    "name": "Tahini (Thineh) pail 4 kg",
    "lebaneseName": "Thineh",
    "description": "Stone-ground sesame paste and traditional herb blends, prepared the homemade way.",
    "format": "4 kg",
    "price": 17,
    "currency": "USD",
    "priceBasis": "item",
    "order": 14,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "zaatar-kham-016-tahini-zaatar",
    "categoryId": "tahini-zaatar",
    "name": "Zaatar kham",
    "lebaneseName": "",
    "description": "Stone-ground sesame paste and traditional herb blends, prepared the homemade way.",
    "format": "",
    "price": 8.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 16,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "zaatar-mix-1-kg-017-tahini-zaatar",
    "categoryId": "tahini-zaatar",
    "name": "Zaatar Mix 1 kg",
    "lebaneseName": "",
    "description": "Stone-ground sesame paste and traditional herb blends, prepared the homemade way.",
    "format": "1 kg",
    "price": 8.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 17,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "zaatar-mix-250-018-tahini-zaatar",
    "categoryId": "tahini-zaatar",
    "name": "Zaatar Mix 250",
    "lebaneseName": "",
    "description": "Stone-ground sesame paste and traditional herb blends, prepared the homemade way.",
    "format": "",
    "price": 2.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 18,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "zaatar-mix-500-019-tahini-zaatar",
    "categoryId": "tahini-zaatar",
    "name": "Zaatar Mix 500",
    "lebaneseName": "",
    "description": "Stone-ground sesame paste and traditional herb blends, prepared the homemade way.",
    "format": "",
    "price": 5.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 19,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olives-black-650-g-001-olives",
    "categoryId": "olives",
    "name": "Olives black 650 g",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "650 g",
    "price": 2.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 1,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olives-black-pail-zero-10-kg-002-olives",
    "categoryId": "olives",
    "name": "Olives Black pail zero 10 kg",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "10 kg",
    "price": 4.89,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 2,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olives-black-sliced-650-g-003-olives",
    "categoryId": "olives",
    "name": "Olives black sliced 650 g",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "650 g",
    "price": 2.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 3,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olives-black-sliced-650-g-oil-004-olives",
    "categoryId": "olives",
    "name": "Olives black sliced 650 g + oil",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "650 g",
    "price": 4.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 4,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olives-black-green-650-oil-005-olives",
    "categoryId": "olives",
    "name": "Olives black/green 650 + oil",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "",
    "price": 4.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 5,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olives-green-650-g-006-olives",
    "categoryId": "olives",
    "name": "Olives green 650 g",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "650 g",
    "price": 2.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 6,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olives-grilled-salad-650-g-007-olives",
    "categoryId": "olives",
    "name": "Olives grilled Salad 650 g",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "650 g",
    "price": 2.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 7,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olives-pail-black-10-kg-008-olives",
    "categoryId": "olives",
    "name": "Olives Pail black 10 kg",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "10 kg",
    "price": 4.2,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 8,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olives-pail-green-10-kg-009-olives",
    "categoryId": "olives",
    "name": "Olives Pail green 10 kg",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "10 kg",
    "price": 4.2,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 9,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olives-pail-sliced-10-kg-010-olives",
    "categoryId": "olives",
    "name": "Olives Pail sliced 10 kg",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "10 kg",
    "price": 4.2,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 10,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olives-spanish-grilled-650-g-011-olives",
    "categoryId": "olives",
    "name": "Olives Spanish grilled 650 g",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "650 g",
    "price": 2.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 11,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olives-spanish-grilled-kg-012-olives",
    "categoryId": "olives",
    "name": "Olives Spanish Grilled kg",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "",
    "price": 4.5,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 12,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olives-stuffed-7arr-650-g-013-olives",
    "categoryId": "olives",
    "name": "Olives stuffed 7arr 650 g",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "650 g",
    "price": 3.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 13,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olives-stuffed-almonds-650-g-014-olives",
    "categoryId": "olives",
    "name": "Olives stuffed almonds 650 g",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "650 g",
    "price": 3.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 14,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olives-stuffed-mix-pail-kg-015-olives",
    "categoryId": "olives",
    "name": "Olives Stuffed Mix pail kg",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "",
    "price": 5.5,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 15,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olives-stuffed-walnut-650-g-016-olives",
    "categoryId": "olives",
    "name": "Olives stuffed walnut 650 g",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "650 g",
    "price": 3.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 16,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "olivese-black-1-kg-017-olives",
    "categoryId": "olives",
    "name": "Olives black 1 kg",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "1 kg",
    "price": 4.2,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 17,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-19"
  },
  {
    "id": "olivese-sliced-1-kg-018-olives",
    "categoryId": "olives",
    "name": "Olives Sliced 1 kg",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "1 kg",
    "price": 4,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 18,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-19"
  },
  {
    "id": "zeitoun-green-pail-zero-10kg-019-olives",
    "categoryId": "olives",
    "name": "Zeitoun green pail zero 10kg",
    "lebaneseName": "",
    "description": "Hand-cured Lebanese olives, prepared using traditional methods.",
    "format": "10kg",
    "price": 45,
    "currency": "USD",
    "priceBasis": "item",
    "order": 19,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "7arr-gazal-5-kg-001-pickles",
    "categoryId": "pickles",
    "name": "7arr Gazal 5 kg /Pail",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "5 kg",
    "price": 10,
    "currency": "USD",
    "priceBasis": "item",
    "order": 1,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "7arr-gazal-7-kg-002-pickles",
    "categoryId": "pickles",
    "name": "7arr Gazal 7 kg /Pail",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "7 kg",
    "price": 2,
    "currency": "USD",
    "priceBasis": "item",
    "order": 2,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "7arr-pail-rafi3-5-kg-003-pickles",
    "categoryId": "pickles",
    "name": "7arr pail Rafi3 5 kg",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "5 kg",
    "price": 12.5,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 3,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "cornichon-620g-004-pickles",
    "categoryId": "pickles",
    "name": "Cornichon 620g",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "620g",
    "price": 2.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 4,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "cornichons-pail-10-kg-005-pickles",
    "categoryId": "pickles",
    "name": "Cornichons Pail 10 kg",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "10 kg",
    "price": 4,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 5,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "left-7abb-pail-10-kg-006-pickles",
    "categoryId": "pickles",
    "name": "Left 7abb pail 10 kg",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "10 kg",
    "price": 10,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 6,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "left-mcharra7-pail-10-kg-007-pickles",
    "categoryId": "pickles",
    "name": "Left mcharra7 pail 10 kg",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "10 kg",
    "price": 15,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 7,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "makdous-560g-008-pickles",
    "categoryId": "pickles",
    "name": "Makdous 560g",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "560g",
    "price": 4.75,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 8,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "makdouss-pail-10-kg-walnut-010-pickles",
    "categoryId": "pickles",
    "name": "Makdouss pail 10 kg +walnut",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "10 kg",
    "price": 5.5,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 10,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "me2tti-mchara7-pail-10-kg-011-pickles",
    "categoryId": "pickles",
    "name": "Me2tti mchara7 pail 10 kg",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "10 kg",
    "price": 11,
    "currency": "USD",
    "priceBasis": "item",
    "order": 11,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pickles-7ar-gazal-500g-012-pickles",
    "categoryId": "pickles",
    "name": "Pickles 7ar Gazal 500g",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "500g",
    "price": 1.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 12,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pickles-khiar-mchara7-pail-10-kg-014-pickles",
    "categoryId": "pickles",
    "name": "Pickles Khiar mchara7 Pail 10 kg",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "10 kg",
    "price": 11,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 14,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pickles-khiar-zahra-pail-10-kg-015-pickles",
    "categoryId": "pickles",
    "name": "Pickles Khiar zahra Pail 10 kg",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "10 kg",
    "price": 22,
    "currency": "USD",
    "priceBasis": "item",
    "order": 15,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pickles-khiar-zikzak-pail-10-kg-016-pickles",
    "categoryId": "pickles",
    "name": "Pickles khiar zikzak pail 10 kg",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "10 kg",
    "price": 12,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 16,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pickles-mchakal-90g-017-pickles",
    "categoryId": "pickles",
    "name": "Pickles Mchakal 90g",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "90g",
    "price": 0.21,
    "currency": "USD",
    "priceBasis": "item",
    "order": 17,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pickles-mchakal-pail-10-kg-018-pickles",
    "categoryId": "pickles",
    "name": "Pickles mchakal Pail 10 kg",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "10 kg",
    "price": 12,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 18,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pickles-mchakkal-620-g-019-pickles",
    "categoryId": "pickles",
    "name": "Pickles mchakkal 620 g",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "620 g",
    "price": 1.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 19,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pickles-me2tti-620-g-021-pickles",
    "categoryId": "pickles",
    "name": "Pickles me2tti 620 g",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "620 g",
    "price": 1.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 21,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pickles-me2tti-zahra-pail-10-k-022-pickles",
    "categoryId": "pickles",
    "name": "Pickles me2tti zahra pail 10 k",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "",
    "price": 2.2,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 22,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pickles-ziczac-pail-10-kg-023-pickles",
    "categoryId": "pickles",
    "name": "Pickles ziczac pail 10 kg",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "10 kg",
    "price": 1.33,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 23,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "warak-3arish-550-g-024-pickles",
    "categoryId": "pickles",
    "name": "Warak 3arish 550 g",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "550 g",
    "price": 3.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 24,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "warak-enab-pail-10-kg-026-pickles",
    "categoryId": "pickles",
    "name": "Warak Enab pail 10 kg",
    "lebaneseName": "",
    "description": "Traditional Lebanese pickled vegetables, naturally preserved.",
    "format": "10 kg",
    "price": 4.2,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 26,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "debs-kharroub-carob-molasses-1-kg-001-molasses-vinegars",
    "categoryId": "molasses-vinegars",
    "name": "Debs Kharroub (Carob Molasses) 1 kg",
    "lebaneseName": "Debs Kharroub",
    "description": "Traditional Lebanese molasses and natural acids, slow-reduced by hand.",
    "format": "1 kg",
    "price": 4,
    "currency": "USD",
    "priceBasis": "item",
    "order": 1,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "debs-kharroub-carob-molasses-500-g-002-molasses-vinegars",
    "categoryId": "molasses-vinegars",
    "name": "Debs Kharroub (Carob Molasses) 500 g",
    "lebaneseName": "Debs Kharroub",
    "description": "Traditional Lebanese molasses and natural acids, slow-reduced by hand.",
    "format": "500 g",
    "price": 2.25,
    "currency": "USD",
    "priceBasis": "item",
    "order": 2,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "debs-remman-pomegranate-molasses-250ml-003-molasses-vinegars",
    "categoryId": "molasses-vinegars",
    "name": "Debs Remman (Pomegranate Molasses) 250ml",
    "lebaneseName": "Debs Remman",
    "description": "Traditional Lebanese molasses and natural acids, slow-reduced by hand.",
    "format": "250ml",
    "price": 2,
    "currency": "USD",
    "priceBasis": "item",
    "order": 3,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "debs-remman-pomegranate-molasses-500-ml-004-molasses-vinegars",
    "categoryId": "molasses-vinegars",
    "name": "Debs Remman (Pomegranate Molasses) 500 ml",
    "lebaneseName": "Debs Remman",
    "description": "Traditional Lebanese molasses and natural acids, slow-reduced by hand.",
    "format": "500 ml",
    "price": 3.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 4,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "debs-remman-pomegranate-molasses-gallon--005-molasses-vinegars",
    "categoryId": "molasses-vinegars",
    "name": "Debs Remman (Pomegranate Molasses) gallon 6.25 kg",
    "lebaneseName": "Debs Remman",
    "description": "Traditional Lebanese molasses and natural acids, slow-reduced by hand.",
    "format": "6.25 kg",
    "price": 2.88,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 5,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "debs-tamer-date-molasses-1-kg-006-molasses-vinegars",
    "categoryId": "molasses-vinegars",
    "name": "Debs Tamer (Date Molasses) 1 kg",
    "lebaneseName": "Debs Tamer",
    "description": "Traditional Lebanese molasses and natural acids, slow-reduced by hand.",
    "format": "1 kg",
    "price": 5.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 6,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "debs-tamer-date-molasses-500g-007-molasses-vinegars",
    "categoryId": "molasses-vinegars",
    "name": "Debs Tamer (Date Molasses) 500g",
    "lebaneseName": "Debs Tamer",
    "description": "Traditional Lebanese molasses and natural acids, slow-reduced by hand.",
    "format": "500g",
    "price": 3,
    "currency": "USD",
    "priceBasis": "item",
    "order": 7,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "hamod-el-hosrom-verjuice-250-ml-008-molasses-vinegars",
    "categoryId": "molasses-vinegars",
    "name": "Hamod el Hosrom (Verjuice) 250 ml",
    "lebaneseName": "Hamod el Hosrom",
    "description": "Traditional Lebanese molasses and natural acids, slow-reduced by hand.",
    "format": "250 ml",
    "price": 2.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 8,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "hamod-el-hosrom-verjuice-500-ml-009-molasses-vinegars",
    "categoryId": "molasses-vinegars",
    "name": "Hamod el Hosrom (Verjuice) 500 ml",
    "lebaneseName": "Hamod el Hosrom",
    "description": "Traditional Lebanese molasses and natural acids, slow-reduced by hand.",
    "format": "500 ml",
    "price": 4.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 9,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "khal-el-assal-750-ml-010-molasses-vinegars",
    "categoryId": "molasses-vinegars",
    "name": "Khal el Assal 750 ml",
    "lebaneseName": "",
    "description": "Traditional Lebanese molasses and natural acids, slow-reduced by hand.",
    "format": "750 ml",
    "price": 8,
    "currency": "USD",
    "priceBasis": "item",
    "order": 10,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "natural-apple-vinegar-375-ml-011-molasses-vinegars",
    "categoryId": "molasses-vinegars",
    "name": "Natural Apple Vinegar 375 ml",
    "lebaneseName": "",
    "description": "Traditional Lebanese molasses and natural acids, slow-reduced by hand.",
    "format": "375 ml",
    "price": 1.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 11,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "natural-apple-vinegar-750-ml-012-molasses-vinegars",
    "categoryId": "molasses-vinegars",
    "name": "Natural Apple Vinegar 750 ml",
    "lebaneseName": "",
    "description": "Traditional Lebanese molasses and natural acids, slow-reduced by hand.",
    "format": "750 ml",
    "price": 3.25,
    "currency": "USD",
    "priceBasis": "item",
    "order": 12,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "natural-apple-vinegar-kg-013-molasses-vinegars",
    "categoryId": "molasses-vinegars",
    "name": "Natural Apple Vinegar kg",
    "lebaneseName": "",
    "description": "Traditional Lebanese molasses and natural acids, slow-reduced by hand.",
    "format": "",
    "price": 2.5,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 13,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "natural-debs-remman-pomegranate-molasses-014-molasses-vinegars",
    "categoryId": "molasses-vinegars",
    "name": "Natural Debs Remman (Pomegranate Molasses) 1 kg",
    "lebaneseName": "Natural Debs Remman",
    "description": "Traditional Lebanese molasses and natural acids, slow-reduced by hand.",
    "format": "1 kg",
    "price": 11,
    "currency": "USD",
    "priceBasis": "item",
    "order": 14,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "white-vinegar-gallon-nice-food-5l-016-molasses-vinegars",
    "categoryId": "molasses-vinegars",
    "name": "White vinegar gallon 5L",
    "lebaneseName": "",
    "description": "Traditional Lebanese molasses and natural acids, slow-reduced by hand.",
    "format": "5L",
    "price": 2,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 16,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "apricot-jam-650-g-001-jams",
    "categoryId": "jams",
    "name": "Apricot jam 650 g",
    "lebaneseName": "",
    "description": "Homemade fruit preserve, cooked slowly the traditional way.",
    "format": "650 g",
    "price": 2.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 1,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "black-mulbery-jam-650-g-002-jams",
    "categoryId": "jams",
    "name": "Black Mulbery Jam 650 g",
    "lebaneseName": "",
    "description": "Homemade fruit preserve, cooked slowly the traditional way.",
    "format": "650 g",
    "price": 2.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 2,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "fig-jam-650-g-003-jams",
    "categoryId": "jams",
    "name": "Fig jam 650 g",
    "lebaneseName": "",
    "description": "Homemade fruit preserve, cooked slowly the traditional way.",
    "format": "650 g",
    "price": 3,
    "currency": "USD",
    "priceBasis": "item",
    "order": 3,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "mulberry-jam-650-g-004-jams",
    "categoryId": "jams",
    "name": "Mulberry jam 650 g",
    "lebaneseName": "",
    "description": "Homemade fruit preserve, cooked slowly the traditional way.",
    "format": "650 g",
    "price": 2.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 4,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "strawberry-jam-650g-005-jams",
    "categoryId": "jams",
    "name": "Strawberry jam 650g",
    "lebaneseName": "",
    "description": "Homemade fruit preserve, cooked slowly the traditional way.",
    "format": "650g",
    "price": 2.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 5,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "kas3in-250-ml-001-syrups-waters",
    "categoryId": "syrups-waters",
    "name": "Kas3in 250 ml",
    "lebaneseName": "",
    "description": "Traditional Lebanese floral water or syrup, distilled and prepared naturally.",
    "format": "250 ml",
    "price": 2.3,
    "currency": "USD",
    "priceBasis": "item",
    "order": 1,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "kas3in-500-ml-002-syrups-waters",
    "categoryId": "syrups-waters",
    "name": "Kas3in 500 ml",
    "lebaneseName": "",
    "description": "Traditional Lebanese floral water or syrup, distilled and prepared naturally.",
    "format": "500 ml",
    "price": 4.25,
    "currency": "USD",
    "priceBasis": "item",
    "order": 2,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "ma2-el-wared-rose-water-250-ml-004-syrups-waters",
    "categoryId": "syrups-waters",
    "name": "Ma2 el Wared (Rose Water) 250 ml",
    "lebaneseName": "",
    "description": "Traditional Lebanese floral water or syrup, distilled and prepared naturally.",
    "format": "250 ml",
    "price": 4,
    "currency": "USD",
    "priceBasis": "item",
    "order": 4,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "ma2-el-wared-rose-water-500-ml-005-syrups-waters",
    "categoryId": "syrups-waters",
    "name": "Ma2 el Wared (Rose Water) 500 ml",
    "lebaneseName": "",
    "description": "Traditional Lebanese floral water or syrup, distilled and prepared naturally.",
    "format": "500 ml",
    "price": 8,
    "currency": "USD",
    "priceBasis": "item",
    "order": 5,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "ma2-el-zaher-orange-blossom-water-250-ml-006-syrups-waters",
    "categoryId": "syrups-waters",
    "name": "Ma2 el Zaher (Orange Blossom Water) 250 ml",
    "lebaneseName": "",
    "description": "Traditional Lebanese floral water or syrup, distilled and prepared naturally.",
    "format": "250 ml",
    "price": 5.25,
    "currency": "USD",
    "priceBasis": "item",
    "order": 6,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "ma2-el-zaher-orange-blossom-water-500-ml-007-syrups-waters",
    "categoryId": "syrups-waters",
    "name": "Ma2 el Zaher (Orange Blossom Water) 500 ml",
    "lebaneseName": "",
    "description": "Traditional Lebanese floral water or syrup, distilled and prepared naturally.",
    "format": "500 ml",
    "price": 10,
    "currency": "USD",
    "priceBasis": "item",
    "order": 7,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sharab-boussfeir-bitter-orange-syrup-750-008-syrups-waters",
    "categoryId": "syrups-waters",
    "name": "Sharab Boussfeir (Blossom Orange Syrup) 750 ml",
    "lebaneseName": "Sharab Boussfeir",
    "description": "Traditional Lebanese floral water or syrup, distilled and prepared naturally.",
    "format": "750 ml",
    "price": 6,
    "currency": "USD",
    "priceBasis": "item",
    "order": 8,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sharab-boussfeir-500-ml-009-syrups-waters",
    "categoryId": "syrups-waters",
    "name": "Sharab boussfeir 500 ml",
    "lebaneseName": "",
    "description": "Traditional Lebanese floral water or syrup, distilled and prepared naturally.",
    "format": "500 ml",
    "price": 4,
    "currency": "USD",
    "priceBasis": "item",
    "order": 9,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sharab-el-tout-mulberry-syrup-500-ml-012-syrups-waters",
    "categoryId": "syrups-waters",
    "name": "Sharab el Tout (Mulberry Syrup) 500 ml",
    "lebaneseName": "Sharab el Tout",
    "description": "Traditional Lebanese floral water or syrup, distilled and prepared naturally.",
    "format": "500 ml",
    "price": 7.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 12,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sharab-el-tout-mulberry-syrup-750-ml-013-syrups-waters",
    "categoryId": "syrups-waters",
    "name": "Sharab el Tout (Mulberry Syrup) 750 ml",
    "lebaneseName": "Sharab el Tout",
    "description": "Traditional Lebanese floral water or syrup, distilled and prepared naturally.",
    "format": "750 ml",
    "price": 11,
    "currency": "USD",
    "priceBasis": "item",
    "order": 13,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sharab-el-wared-rose-syrup-500-ml-016-syrups-waters",
    "categoryId": "syrups-waters",
    "name": "Sharab el Wared (Rose Syrup) 500 ml",
    "lebaneseName": "Sharab el Wared",
    "description": "Traditional Lebanese floral water or syrup, distilled and prepared naturally.",
    "format": "500 ml",
    "price": 7.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 16,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sharab-el-wared-rose-syrup-750-ml-017-syrups-waters",
    "categoryId": "syrups-waters",
    "name": "Sharab el Wared (Rose Syrup) 750 ml",
    "lebaneseName": "Sharab el Wared",
    "description": "Traditional Lebanese floral water or syrup, distilled and prepared naturally.",
    "format": "750 ml",
    "price": 11,
    "currency": "USD",
    "priceBasis": "item",
    "order": 17,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "almond-001-dried-fruits",
    "categoryId": "dried-fruits",
    "name": "Almond",
    "lebaneseName": "",
    "description": "Naturally dried fruit, date or nut — a traditional Lebanese pantry staple.",
    "format": "",
    "price": 12,
    "currency": "USD",
    "priceBasis": "item",
    "order": 1,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "coconut-crushed-1-kg-002-dried-fruits",
    "categoryId": "dried-fruits",
    "name": "Coconut crushed 1 kg",
    "lebaneseName": "",
    "description": "Naturally dried fruit, date or nut — a traditional Lebanese pantry staple.",
    "format": "1 kg",
    "price": 9,
    "currency": "USD",
    "priceBasis": "item",
    "order": 2,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "coconut-crushed-250-g-003-dried-fruits",
    "categoryId": "dried-fruits",
    "name": "Coconut crushed 250 g",
    "lebaneseName": "",
    "description": "Naturally dried fruit, date or nut — a traditional Lebanese pantry staple.",
    "format": "250 g",
    "price": 2.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 3,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "crushed-dates-600g-005-dried-fruits",
    "categoryId": "dried-fruits",
    "name": "Crushed dates 600g",
    "lebaneseName": "",
    "description": "Naturally dried fruit, date or nut — a traditional Lebanese pantry staple.",
    "format": "600g",
    "price": 3.25,
    "currency": "USD",
    "priceBasis": "item",
    "order": 5,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "date-khodary-extra-1kg-006-dried-fruits",
    "categoryId": "dried-fruits",
    "name": "Date khodary Extra 1kg",
    "lebaneseName": "",
    "description": "Naturally dried fruit, date or nut — a traditional Lebanese pantry staple.",
    "format": "1kg",
    "price": 6.25,
    "currency": "USD",
    "priceBasis": "item",
    "order": 6,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "date-khodary-extra-500g-007-dried-fruits",
    "categoryId": "dried-fruits",
    "name": "Date khodary extra 500g",
    "lebaneseName": "",
    "description": "Naturally dried fruit, date or nut — a traditional Lebanese pantry staple.",
    "format": "500g",
    "price": 3.25,
    "currency": "USD",
    "priceBasis": "item",
    "order": 7,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "date-medjoul-008-dried-fruits",
    "categoryId": "dried-fruits",
    "name": "Date Medjoul",
    "lebaneseName": "",
    "description": "Naturally dried fruit, date or nut — a traditional Lebanese pantry staple.",
    "format": "",
    "price": 14,
    "currency": "USD",
    "priceBasis": "item",
    "order": 8,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "dried-apricot-009-dried-fruits",
    "categoryId": "dried-fruits",
    "name": "Dried Apricot",
    "lebaneseName": "",
    "description": "Naturally dried fruit, date or nut — a traditional Lebanese pantry staple.",
    "format": "",
    "price": 20,
    "currency": "USD",
    "priceBasis": "item",
    "order": 9,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "dried-cranberry-010-dried-fruits",
    "categoryId": "dried-fruits",
    "name": "Dried Cranberry",
    "lebaneseName": "",
    "description": "Naturally dried fruit, date or nut — a traditional Lebanese pantry staple.",
    "format": "",
    "price": 16,
    "currency": "USD",
    "priceBasis": "item",
    "order": 10,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "dried-fig-011-dried-fruits",
    "categoryId": "dried-fruits",
    "name": "Dried fig",
    "lebaneseName": "",
    "description": "Naturally dried fruit, date or nut — a traditional Lebanese pantry staple.",
    "format": "",
    "price": 18,
    "currency": "USD",
    "priceBasis": "item",
    "order": 11,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "dried-fruits-decorated-650g-013-dried-fruits",
    "categoryId": "dried-fruits",
    "name": "Dried fruits Decorated 650g",
    "lebaneseName": "",
    "description": "Naturally dried fruit, date or nut — a traditional Lebanese pantry staple.",
    "format": "650g",
    "price": 10.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 13,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "dried-fruits-decoreted-830g-014-dried-fruits",
    "categoryId": "dried-fruits",
    "name": "Dried fruits Decoreted 830g",
    "lebaneseName": "",
    "description": "Naturally dried fruit, date or nut — a traditional Lebanese pantry staple.",
    "format": "830g",
    "price": 13.25,
    "currency": "USD",
    "priceBasis": "item",
    "order": 14,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "dried-prune-015-dried-fruits",
    "categoryId": "dried-fruits",
    "name": "Dried Prune",
    "lebaneseName": "",
    "description": "Naturally dried fruit, date or nut — a traditional Lebanese pantry staple.",
    "format": "",
    "price": 13,
    "currency": "USD",
    "priceBasis": "item",
    "order": 15,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pistachio-016-dried-fruits",
    "categoryId": "dried-fruits",
    "name": "Pistachio",
    "lebaneseName": "",
    "description": "Naturally dried fruit, date or nut — a traditional Lebanese pantry staple.",
    "format": "",
    "price": 30,
    "currency": "USD",
    "priceBasis": "item",
    "order": 16,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "raisin-1kg-017-dried-fruits",
    "categoryId": "dried-fruits",
    "name": "Raisin 1kg",
    "lebaneseName": "",
    "description": "Naturally dried fruit, date or nut — a traditional Lebanese pantry staple.",
    "format": "1kg",
    "price": 9,
    "currency": "USD",
    "priceBasis": "item",
    "order": 17,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "raisin-250g-018-dried-fruits",
    "categoryId": "dried-fruits",
    "name": "Raisin 250g",
    "lebaneseName": "",
    "description": "Naturally dried fruit, date or nut — a traditional Lebanese pantry staple.",
    "format": "250g",
    "price": 2.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 18,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "walnut-019-dried-fruits",
    "categoryId": "dried-fruits",
    "name": "Walnut",
    "lebaneseName": "",
    "description": "Naturally dried fruit, date or nut — a traditional Lebanese pantry staple.",
    "format": "",
    "price": 12,
    "currency": "USD",
    "priceBasis": "item",
    "order": 19,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "bbq-sauce-plastic-gallon-4-2-kg-001-tomato",
    "categoryId": "tomato",
    "name": "BBQ Sauce Plastic Gallon 4.2 kg",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "4.2 kg",
    "price": 7.62,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 1,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "chicken-wings-plastic-gallon-2-2-kg-002-tomato",
    "categoryId": "tomato",
    "name": "Chicken Wings Sauce Plastic Gallon 2.2 kg ",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "2.2 kg",
    "price": 4,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 2,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "ketchup-340-g-003-tomato",
    "categoryId": "tomato",
    "name": "Ketchup 340 g",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "340 g",
    "price": 1.15,
    "currency": "USD",
    "priceBasis": "item",
    "order": 3,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "ketchup-plastic-gallon-4-2-kg-004-tomato",
    "categoryId": "tomato",
    "name": "Ketchup Plastic Gallon 4.2 kg",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "4.2 kg",
    "price": 4.75,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 4,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "mayonnaise-classic-us-plastic-gallon-3-8-005-tomato",
    "categoryId": "tomato",
    "name": "Mayonnaise Classic US Plastic Gallon 3.8 kg",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "3.8 kg",
    "price": 10,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 5,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "mayonnaise-heavy-us-plastic-gallon-3-8-k-006-tomato",
    "categoryId": "tomato",
    "name": "Mayonnaise Heavy US Plastic Gallon 3.8 kg",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "3.8 kg",
    "price": 11.75,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 6,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "mustard-us-plastic-gallon-4-2-kg-007-tomato",
    "categoryId": "tomato",
    "name": "Mustard US Plastic Gallon 4.2 kg",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "4.2 kg",
    "price": 8.62,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 7,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pasta-sauce-2-750-kg-008-tomato",
    "categoryId": "tomato",
    "name": "Pasta Sauce 2.750 kg",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "2.750 kg",
    "price": 3.5,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 8,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pizza-sauce-fine-herbs-300-g-009-tomato",
    "categoryId": "tomato",
    "name": "Pizza Sauce Fine Herbs 300 g",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "300 g",
    "price": 2,
    "currency": "USD",
    "priceBasis": "item",
    "order": 9,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pizza-sauce-fine-herbs-370-g-010-tomato",
    "categoryId": "tomato",
    "name": "Pizza sauce Fine Herbs 370 g",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "370 g",
    "price": 2.25,
    "currency": "USD",
    "priceBasis": "item",
    "order": 10,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pizza-sauce-green-pepper-300-g-011-tomato",
    "categoryId": "tomato",
    "name": "Pizza Sauce Green Pepper 300 g",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "300 g",
    "price": 2,
    "currency": "USD",
    "priceBasis": "item",
    "order": 11,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "pizza-sauce-green-pepper-370-g-012-tomato",
    "categoryId": "tomato",
    "name": "Pizza Sauce Green Pepper 370 g",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "370 g",
    "price": 2.25,
    "currency": "USD",
    "priceBasis": "item",
    "order": 12,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sweet-chilli-plastic-gallon-2-2-kg-013-tomato",
    "categoryId": "tomato",
    "name": "Sweet & chilli Plastic Gallon 2.2 kg",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "2.2 kg",
    "price": 4,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 13,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "sweet-sour-plastic-gallon-2-2-kg-014-tomato",
    "categoryId": "tomato",
    "name": "Sweet & sour Plastic Gallon 2.2 kg",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "2.2 kg",
    "price": 4,
    "currency": "USD",
    "priceBasis": "kg",
    "order": 14,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "tomato-paste-1300-g-016-tomato",
    "categoryId": "tomato",
    "name": "Tomato Paste 1300 g / 6pcs",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "1300 g",
    "price": 3.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 16,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "tomato-paste-300g-017-tomato",
    "categoryId": "tomato",
    "name": "Tomato paste 300g",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "300g",
    "price": 1.75,
    "currency": "USD",
    "priceBasis": "item",
    "order": 17,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "tomato-paste-650-g-018-tomato",
    "categoryId": "tomato",
    "name": "Tomato Paste 650 g",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "650 g",
    "price": 1.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 18,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "tomato-paste-opre-660-g-019-tomato",
    "categoryId": "tomato",
    "name": "Tomato Paste Opre 660 g",
    "lebaneseName": "",
    "description": "Traditional homemade tomato-based sauce or condiment.",
    "format": "660 g",
    "price": 3,
    "currency": "USD",
    "priceBasis": "item",
    "order": 19,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "liquor-apple-250-ml-001-liqueurs",
    "categoryId": "liqueurs",
    "name": "Liquor/ Apple 250 ml",
    "lebaneseName": "",
    "description": "Traditional Lebanese homemade liqueur, infused the artisanal way.",
    "format": "250 ml",
    "price": 4.25,
    "currency": "USD",
    "priceBasis": "item",
    "order": 1,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "liquor-apple-500-ml-002-liqueurs",
    "categoryId": "liqueurs",
    "name": "Liquor/ Apple 500 ml",
    "lebaneseName": "",
    "description": "Traditional Lebanese homemade liqueur, infused the artisanal way.",
    "format": "500 ml",
    "price": 8,
    "currency": "USD",
    "priceBasis": "item",
    "order": 2,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "liquor-cherry-250-ml-003-liqueurs",
    "categoryId": "liqueurs",
    "name": "Liquor/ Cherry 250 ml",
    "lebaneseName": "",
    "description": "Traditional Lebanese homemade liqueur, infused the artisanal way.",
    "format": "250 ml",
    "price": 4.25,
    "currency": "USD",
    "priceBasis": "item",
    "order": 3,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "liquor-cherry-500-ml-004-liqueurs",
    "categoryId": "liqueurs",
    "name": "Liquor/ Cherry 500 ml",
    "lebaneseName": "",
    "description": "Traditional Lebanese homemade liqueur, infused the artisanal way.",
    "format": "500 ml",
    "price": 8,
    "currency": "USD",
    "priceBasis": "item",
    "order": 4,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "liquor-myrtle-henbless-250-ml-005-liqueurs",
    "categoryId": "liqueurs",
    "name": "Liquor/ Myrtle Henbless 250 ml",
    "lebaneseName": "",
    "description": "Traditional Lebanese homemade liqueur, infused the artisanal way.",
    "format": "250 ml",
    "price": 4.25,
    "currency": "USD",
    "priceBasis": "item",
    "order": 5,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "liquor-myrtle-henbless-500-ml-006-liqueurs",
    "categoryId": "liqueurs",
    "name": "Liquor/ Myrtle Henbless 500 ml",
    "lebaneseName": "",
    "description": "Traditional Lebanese homemade liqueur, infused the artisanal way.",
    "format": "500 ml",
    "price": 8,
    "currency": "USD",
    "priceBasis": "item",
    "order": 6,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "coffret-large-creamy-honey-001-gift-boxes",
    "categoryId": "gift-boxes",
    "name": "Coffret Large Creamy Honey",
    "lebaneseName": "",
    "description": "A curated OPRE NATURE gift set, ready for sharing.",
    "format": "",
    "price": 85,
    "currency": "USD",
    "priceBasis": "item",
    "order": 1,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "coffret-large-pollen-002-gift-boxes",
    "categoryId": "gift-boxes",
    "name": "Coffret Large Pollen",
    "lebaneseName": "",
    "description": "A curated OPRE NATURE gift set, ready for sharing.",
    "format": "",
    "price": 85,
    "currency": "USD",
    "priceBasis": "item",
    "order": 2,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "coffret-small-creamy-honey-003-gift-boxes",
    "categoryId": "gift-boxes",
    "name": "Coffret Small Creamy Honey",
    "lebaneseName": "",
    "description": "A curated OPRE NATURE gift set, ready for sharing.",
    "format": "",
    "price": 50,
    "currency": "USD",
    "priceBasis": "item",
    "order": 3,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "coffret-small-pollen-004-gift-boxes",
    "categoryId": "gift-boxes",
    "name": "Coffret small Pollen",
    "lebaneseName": "",
    "description": "A curated OPRE NATURE gift set, ready for sharing.",
    "format": "",
    "price": 50,
    "currency": "USD",
    "priceBasis": "item",
    "order": 4,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "7ar-shatta-001-other",
    "categoryId": "other",
    "name": "7ar shatta",
    "lebaneseName": "",
    "description": "A traditional OPRE NATURE specialty, prepared the homemade way.",
    "format": "",
    "price": 3,
    "currency": "USD",
    "priceBasis": "item",
    "order": 1,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "mashrouk-400-002-other",
    "categoryId": "other",
    "name": "Date Mashrouk 400",
    "lebaneseName": "",
    "description": "A traditional OPRE NATURE specialty, prepared the homemade way.",
    "format": "",
    "price": 1,
    "currency": "USD",
    "priceBasis": "item",
    "order": 2,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "mashrouk-800g-003-other",
    "categoryId": "other",
    "name": "Date Mashrouk 800g",
    "lebaneseName": "",
    "description": "A traditional OPRE NATURE specialty, prepared the homemade way.",
    "format": "800g",
    "price": 2,
    "currency": "USD",
    "priceBasis": "item",
    "order": 3,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  },
  {
    "id": "prod-msz506nq-t30cu1",
    "categoryId": "molasses-vinegars",
    "name": "White vinegar 1L",
    "lebaneseName": "",
    "description": "Traditional Lebanese molasses and natural acids, slow-reduced by hand.",
    "format": "5L",
    "price": 0.5,
    "currency": "USD",
    "priceBasis": "item",
    "order": 17,
    "active": true,
    "image": "",
    "notes": "",
    "createdDate": "2026-08-18",
    "modifiedDate": "2026-08-18"
  }
];

  const ORIGINAL_SETTINGS = {
  "publicCatalogueUrl": "https://contactleepgroup69.github.io/opre-nature-catalogue/",
  "currency": "USD",
  "catalogueUpdatedDate": "20 August 2026",
  "companyName": "OPRE NATURE",
  "tagline": "Hand Made Natural Products",
  "subTagline": "From Our Fields to Your Table",
  "address": "Fidar, Lebanon - 508 Str.",
  "phone": "+961 3 965708",
  "email": "oprenature@gmail.com",
  "website": "www.oprenature.com",
  "instagram": "@oprenature",
  "aboutText": "Opré means ‘in the fields,’ a name that reflects our deep connection to the land, local agriculture and traditional Lebanese food.\n\nAt OPRE NATURE, our products are carefully prepared with passion using locally cultivated ingredients and time-honoured homemade methods. From olive oil, honey and zaatar to preserves, molasses, dried fruits and traditional specialties, every product celebrates authentic flavour and the generosity of our fields.\n\nWe are committed to offering natural, carefully crafted products that bring the warmth and authenticity of Lebanese homemade food to every table.\n\nAll OPRE NATURE products are gluten-free.",
  "pricingNotice": "All prices are in USD and include VAT. Prices are subject to change; please contact us for the latest update. Prices marked “/ kg” or “/ ml” are unit prices for the indicated professional format."
};

  const ORIGINAL_CATALOGUE = {
    categories: ORIGINAL_CATEGORIES,
    products: ORIGINAL_PRODUCTS,
    settings: ORIGINAL_SETTINGS,
  };

  global.Opre = global.Opre || {};
  global.Opre.Data = {
    ORIGINAL_CATEGORIES,
    ORIGINAL_PRODUCTS,
    ORIGINAL_SETTINGS,
    ORIGINAL_CATALOGUE,
  };
})(window);
